try:
    print(5/0)
except Exception as e:
    print("Error: ",e)
    